version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=BOT_TOKEN
      - Client_ID=Client_ID
      - Client_Secret=Client_Secret
    volumes:
      - .:/usr/src/app
